const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
const React = require('react');
const { renderToStaticMarkup } = require('react-dom/server');
const compile = file => ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.ReactJSX, esModuleInterop: true } }).outputText;
let writes = [], canWrite = true;
const firestore = { collection: (_, ...p) => p.join('/'), doc: (_, ...p) => p.join('/'), serverTimestamp: () => 'NOW', addDoc: async (path, data) => { writes.push({ path, data }); return { id: 'new-contact' }; }, updateDoc: async (path, data) => writes.push({ path, data }) };
const ctx = { exports: {}, require: name => name === 'firebase/firestore' ? firestore : name === './transport-repository' ? { canManageOrganizationLists: () => canWrite } : { db: {} } };
vm.runInNewContext(compile('apps/web/lib/contact-repository.ts'), ctx);
const api = ctx.exports;
const draft = { name: ' Contact ', phone: '081-123-4567', company: 'Company', location: 'Warehouse', notes: 'Call first' };
const actor = { uid: 'admin', organizationId: 'main' };
(async () => {
  assert.equal(await api.saveContact(draft, undefined, actor), 'new-contact');
  assert.equal(writes[0].path, 'organizations/main/contacts'); assert.equal(writes[0].data.name, 'Contact'); assert.equal(writes[0].data.active, true);
  await api.saveContact({ ...draft, phone: '089-999-9999' }, 'existing', actor);
  assert.equal(writes[1].path, 'organizations/main/contacts/existing');
  assert.equal(writes[1].data.active, undefined, 'editing must preserve inactive status');
  assert.ok(writes.every(write => !write.path.includes('today_jobs')), 'contact changes must not rewrite historical jobs');
  await api.setContactActive('existing', false, actor); assert.equal(writes[2].data.active, false);
  for (const bad of [{ name: '' }, { phone: '123' }, { phone: 'javascript:alert(1)' }, { notes: 'x'.repeat(501) }]) assert.throws(() => api.validateContact({ ...draft, ...bad }));
  canWrite = false; await assert.rejects(() => api.saveContact(draft, undefined, actor)); await assert.rejects(() => api.setContactActive('existing', false, actor));
  let value = { id: '', name: '', phone: '', notes: '' };
  const contact = { ...draft, name: 'Contact', id: 'saved', active: true };
  const pickerCtx = { exports: {}, require: name => {
    if (name === 'react') return { ...React, useState: init => [init, () => {}] };
    if (name === './ContactBook') return { useContacts: () => ({ items: [contact], error: '', loading: false }) };
    if (name === '@/lib/transport-repository') return { canManageOrganizationLists: () => true };
    return require(name);
  } };
  vm.runInNewContext(compile('apps/web/app/components/ContactPicker.tsx'), pickerCtx);
  const nodes = node => !node || typeof node !== 'object' ? [] : [node, ...React.Children.toArray(node.props?.children).flatMap(nodes)];
  const render = () => pickerCtx.exports.default({ actor, value, onChange: next => { value = next; } });
  nodes(render()).find(n => n.type === 'select').props.onChange({ target: { value: 'saved' } });
  assert.equal(value.name, 'Contact'); assert.equal(value.phone, draft.phone); assert.equal(value.notes, 'Call first');
  nodes(render()).find(n => n.type === 'input' && n.props.type === 'tel').props.onChange({ target: { value: '089-111-1111' } });
  assert.equal(value.phone, '089-111-1111'); assert.equal(contact.phone, draft.phone, 'job-specific edits must leave directory unchanged');
  const display = { exports: {}, require };
  vm.runInNewContext(compile('apps/web/app/components/JobContacts.tsx'), display);
  const html = renderToStaticMarkup(React.createElement(display.exports.default, { job: { pickupContact: 'Receiver', pickupContactPhone: '081-123-4567', deliveryContact: 'Destination', deliveryContactPhone: '089-111-1111' } }));
  assert.ok(html.includes('tel:0811234567') && html.includes('tel:0891111111'));
  assert.ok(renderToStaticMarkup(React.createElement(display.exports.default, { job: {} })).includes('ยังไม่ระบุผู้ติดต่อ'));
  console.log('PASS: contact validation, company scope, save/edit/archive, permissions, selection, job-only edits, phone links and legacy jobs');
})().catch(error => { console.error(error); process.exitCode = 1; });
