const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
const context = { exports: {}, Date, Intl, Map, Number };
vm.runInNewContext(ts.transpileModule(fs.readFileSync('apps/web/lib/reports.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText, context);
const { deliveryResult, summarizeJobs, filterReportJobs, groupReportJobs, bangkokDate } = context.exports;
const now = Date.parse('2026-09-16T12:00:00+07:00');
const base = { id: '1', workOrder: 'WO-1', jobDate: '2026-09-16', deliveryDate: '2026-09-16', deliveryTime: '10:00', customer: 'A', vehiclePlate: 'กข-1', driverName: 'สมชาย', assignedDriverUid: 'driver-1', organizationId: 'main', carrierName: 'Main', status: 'completed', pickupLocation: 'A', deliveryLocation: 'B' };
const onTime = { ...base, arrivedDeliveryAt: '2026-09-16T03:00:00Z' };
const late = { ...base, id: '2', arrivedDeliveryAt: '2026-09-16T03:00:01Z' };
const overdue = { ...base, id: '3', status: 'to_delivery' };
assert.equal(deliveryResult(onTime, now), 'on_time');
assert.equal(deliveryResult(late, now), 'late');
assert.equal(deliveryResult(overdue, now), 'overdue');
assert.equal(deliveryResult({ ...overdue, deliveryTime: '13:00' }, now), 'pending');
assert.equal(deliveryResult(base, now), 'unknown', 'Do not treat completed jobs as on-time without actual arrival');
assert.equal(deliveryResult({ ...overdue, status: 'arrived_delivery' }, now), 'unknown');
assert.equal(deliveryResult({ ...onTime, deliveryTime: '' }, now), 'unknown');
assert.equal(deliveryResult({ ...late, status: 'cancelled' }, now), 'cancelled');
assert.equal(bangkokDate(new Date('2026-09-15T18:00:00Z')), '2026-09-16');
const jobs = [onTime, late, overdue, { ...base, id: '4' }, { ...late, id: '5', status: 'cancelled' }];
const summary = summarizeJobs(jobs, now);
assert.equal(summary.onTimeRate, 50);
assert.equal(summary.evaluated, 2);
assert.equal(summary.unknown, 1);
assert.equal(summary.overdue, 1);
assert.equal(summary.completed, 3);
assert.equal(summary.trips, 4);
assert.equal(summarizeJobs([], now).onTimeRate, null);
const filters = { start: '2026-09-16', end: '2026-09-16', organization: '', customer: '', search: '', status: '' };
assert.equal(filterReportJobs(jobs, filters, now).length, 5);
assert.equal(filterReportJobs(jobs, { ...filters, status: 'delayed' }, now).length, 2);
assert.equal(filterReportJobs(jobs, { ...filters, search: ' กข-1 ' }, now).length, 5);
assert.equal(filterReportJobs(jobs, { ...filters, organization: 'other' }, now).length, 0);
assert.equal(filterReportJobs([{ ...base, jobDate: undefined }], filters, now).length, 0);
assert.equal(filterReportJobs([{ ...base, jobDate: undefined }], { ...filters, start: '', end: '' }, now).length, 1);
assert.equal(groupReportJobs([onTime, { ...late, assignedDriverUid: 'driver-2' }], 'driver', now).length, 2, 'Different drivers with the same name must not merge');
assert.equal(groupReportJobs([onTime, { ...late, organizationId: 'other' }], 'vehicle', now).length, 2, 'Same plate across organizations must not merge');
assert.equal(groupReportJobs(jobs, 'company', now)[0].onTimeRate, 50);
console.log('PASS: report dates, Bangkok timezone, punctuality, missing data, cancellations, filters, groups and denominators');
